/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.cardapio.UI;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import projeto.cardapio.Bebida;
import projeto.cardapio.Repositorio;

/**
 *
 * @author HTK
 */
public class JFrameListBebida extends javax.swing.JFrame {

    public DefaultTableModel model;
    
    
    public JFrameListBebida() {
        initComponents();
        setLocationRelativeTo(null);
        this.carregarBebidas();
        /*this.setCellRender(tbBebidas, 0, JTableAlign.CENTER());
        this.setCellRender(tbBebidas, 1, JTableAlign.CENTER());
        this.setCellRender(tbBebidas, 2, JTableAlign.CENTER());
        */
    }       
        
    /*public void setCellRender()javax.swing.JTable table, int columnIndex, DefaultTableCellRenderer renderer){
        table.getColumnModel().getColumn(columnIndex).setCellRenderer(renderer);*/
    
    public void carregarBebidas(){
        if(this.model != null)resetTable();
        Repositorio db = new Repositorio();
        Bebida[] bebidas = db.obterListaDeBebidas();
        
        String[] colunas = new String[]{"ID", "Nome"};
        String[][] dados = new String[bebidas.length][colunas.length];
        
        for(int i=0; i < bebidas.length; i++){
            dados[i] = new String[]{
                bebidas[i].getID()+"",
                bebidas[i].getNome()
            };
        }
        this.model = new DefaultTableModel(dados,colunas);
        tbBebida.setModel(this.model);
    }
    
    public void resetTable(){
        this.model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdicionar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbBebida = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista de Bebidas");
        setResizable(false);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        tbBebida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbBebida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRemover)
                .addGap(18, 18, 18)
                .addComponent(btnAdicionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnRemover))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        JFrameBebida jfb = new JFrameBebida();
        jfb.setVisible(true);
        jfb.addWindowListener(new BebidaWindowAdapter(this));
        btnAdicionar.setEnabled(false);
        
         /*JFrameFuncionario jff = new JFrameFuncionario();
        jff.setVisible(true);
        jff.addWindowListener(new FuncionarioWindowAdapter(this));
        btnAdicionar.setEnabled(false);*/
        
        
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        int row = tbBebida.getSelectedRow();
        int ID = Integer.parseInt(tbBebida.getValueAt(row, 0).toString());
        Repositorio db = new Repositorio();
        db.removerBebida(ID);
        this.carregarBebidas();
        
    }//GEN-LAST:event_btnRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameListBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameListBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameListBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameListBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameListBebida().setVisible(true);
            }
        });
    }

    public class BebidaWindowAdapter extends WindowAdapter{
        
        private final JFrameListBebida parent;
        
        public BebidaWindowAdapter(JFrameListBebida parent){
            super();
            this.parent = parent;
        }
        
        @Override
        public void windowClosing(WindowEvent e) {
            parent.carregarBebidas();
            parent.btnAdicionar.setEnabled(true);
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbBebida;
    // End of variables declaration//GEN-END:variables
}
